name: Build

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
          pip install -e .
      - name: Run PyInstaller
        run: |
          python -m PyInstaller.__main__ -F -w -n SmartSpin2kFlasher -i icon.ico esphomeflasher\__main__.py
      - uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: dist/SmartSpin2kFlasher.exe

  build-windows-x86:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x86'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
          pip install -e .
      - name: Run PyInstaller
        run: |
          python -m PyInstaller.__main__ -F -w -n SmartSpin2kFlasher -i icon.ico esphomeflasher\__main__.py
      - name: See dist directory
        run: ls dist
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-x86
          path: dist/SmartSpin2kFlasher.exe

  build-ubuntu:
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Python
       uses: actions/setup-python@v1
       with:
         python-version: '3.7'
     - name: Install dependencies
       run: |
         sudo apt install libgtk-3-dev libnotify-dev libsdl2-dev
         pip install -U \
          -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 \
          wxPython
     - name: Install requirements
       run: |
         pip install -r requirements.txt -r requirements_build.txt
         pip install -e .
     - name: Run PyInstaller
       run: |
         python -m PyInstaller.__main__ -F -w -n SmartSpin2kFlasher -i icon.ico esphomeflasher/__main__.py
     - name: See dist directory
       run: ls dist
     - uses: actions/upload-artifact@v2
       with:
         name: Ubuntu
         path: dist/SmartSpin2kFlasher


  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install requirements
        run: |
          pip install -r requirements.txt -r requirements_build.txt
          pip install -e .
      - name: Run PyInstaller
        run: |
          python -m PyInstaller.__main__ -F -w -n SmartSpin2kFlasher -i icon.icns esphomeflasher/__main__.py
      - name: See dist directory
        run: ls dist
      - name: Move app
        run: |
          mv dist/SmartSpin2kFlasher.app dist/SmartSpin2kFlasher-dev-macOS.app
      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: dist/

  build-pypi:
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Install Python
       uses: actions/setup-python@v1
       with:
         python-version: '3.7'
     - name: Install dependencies
       run: |
         sudo apt install libgtk-3-dev libnotify-dev libsdl2-dev
         pip install -U \
          -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 \
          wxPython
     - name: Install requirements
       run: |
         pip install -r requirements.txt -r requirements_build.txt
         pip install -e .
     - name: Run sdist
       run: python setup.py sdist bdist_wheel
     - name: See dist directory
       run: ls dist
     - uses: actions/upload-artifact@v2
       with:
         name: sdist
         path: dist/smartspin2kflasher-*.tar.gz
     - uses: actions/upload-artifact@v2
       with:
         name: bdist_wheel
         path: dist/smartspin2kflasher-*.whl
